.\" dummy line
.TH GNUPLOT 1 "31 August 1990"
.UC 4
.SH NAME
gnuplot \- an interactive plotting program
.SH SYNOPSIS
.B gnuplot
[ X11 options ] [file ...]
.br
.SH DESCRIPTION
.I Gnuplot 
is a command-driven interactive function plotting program.
.PP
If files are given, 
.I gnuplot 
loads each file with the 
.I load
command, in the order specified.
.I Gnuplot 
exits after the last file is processed.
.PP
Here are some of its features:
.PP
Plots any number of functions, built up of C operators, C library
functions, and some things C doesn't have like **, sgn(), etc.  Also
support for plotting data files, to compare actual
data to theoretical curves.
.PP
User-defined X and Y ranges (optional auto-ranging), smart axes scaling,
smart tic marks.
.PP
Labelling of X and Y axes.
.PP
User-defined constants and functions.
.PP
Support through a generalized graphics driver for
AED 512,
AED 767,
BBN BitGraph,
Commodore Amiga,
Roland DXY800A,
EEPIC,
EmTeX,
Epson 60dpi printers,
Epson LX-800,
Fig, 
HP2623,
HP2648,
HP75xx,
HPGL,
HP LaserJet II,
Imagen,
Iris 4D,
Kermit-MS,
Kyocera laser printer,
LaTeX,
NEC CP6 pinwriter,
PostScript,
QMS QUIC,
ReGis (VT125 and VT2xx),
SCO Xenix CGI,
Selanar,
Star color printer,
Tandy DMP-130 printer,
Tek 401x,
Tek 410x,
Vectrix 384,
VT like tekronix emulator,
Unix PC (ATT 3b1 or ATT 7300),
unixplot,  
and X11.
The PC version compiled by Microsoft C
supports IBM CGA, EGA, VGA, Hercules, ATT 6300,
and Corona 325 graphics.  
The PC version compiled by Turbo C
supports IBM CGA, EGA, MCGA, VGA, Hercules and ATT 6300 graphics.  
Other devices can be added simply, but will require recompiling.
.PP
Shell escapes and command line substitution.
.PP
Load and save capability.
.PP
Output redirection.
.PP
All computations performed in the complex domain.  Just the real part is
plotted by default, but functions like imag() and abs() and arg() are
available to override this.
.SH X11 OPTIONS
.I Gnuplot 
provides two terminal types (\fIx11\fP and \fIX11\fP) for use
with X servers. The \fIX11\fP terminal type provides differing colors as well 
as shapes for the \fIpoints\fP plotting style. The two types are otherwise 
identical.  When used with either of these terminal types, \fIgnuplot\fP
accepts all the standard X Toolkit options and resources such as geometry, font,
and background. See the X(1) man page for a description of
the options. 
.PP
In addition to the X Toolkit options, there are three more
command line options. \fB\-mono\fP forces monochrome rendering on
color displays.
\fB\-gray\fP requests grayscale rendering on grayscale or color displays. 
(Grayscale displays receive monochrome rendering by default.) 
\fB\-clear\fP requests that the window be cleared momentarily before a
new plot is displayed. These options may also be controlled with resources.
For example: \fBgnuplot*gray: on\fP .

For color displays \fIgnuplot\fP honors 
the following resources (shown here with default values):
.sp
.B  "gnuplot*background: white"
.br 
.B  "gnuplot*textColor: black"
.br 
.B  "gnuplot*borderColor: black"
.br 
.B  "gnuplot*axisColor: black"
.br 
.B  "gnuplot*line1Color: red"
.br 
.B  "gnuplot*line2Color: green"
.br 
.B  "gnuplot*line3Color: blue"
.br 
.B  "gnuplot*line4Color: magenta"
.br 
.B  "gnuplot*line5Color: cyan"
.br 
.B  "gnuplot*line6Color: sienna"
.br 
.B  "gnuplot*line7Color: orange"
.br 
.B  "gnuplot*line8Color: coral"
.br 

When \fB\-gray\fP is selected, \fIgnuplot\fP honors 
the following resources for grayscale or color displays (shown here with 
default values). Note that the default background is black.
.sp
.B  "gnuplot*background: black"
.br 
.B  "gnuplot*textGray: white"
.br 
.B  "gnuplot*borderGray: gray50"
.br 
.B  "gnuplot*axisGray: gray50"
.br 
.B  "gnuplot*line1Gray: gray100"
.br 
.B  "gnuplot*line2Gray: gray60"
.br 
.B  "gnuplot*line3Gray: gray80"
.br 
.B  "gnuplot*line4Gray: gray40"
.br 
.B  "gnuplot*line5Gray: gray90"
.br 
.B  "gnuplot*line6Gray: gray50"
.br 
.B  "gnuplot*line7Gray: gray70"
.br 
.B  "gnuplot*line8Gray: gray30"
.br 

.PP
The size or aspect ratio of a plot may be changed by resizing the
.I gnuplot
window.
.SH AUTHORS
Thomas Williams, Pixar Corporation, 
.br
(info-gnuplot@ames.arc.nasa.gov)
.br
and Colin Kelley.
.PP
Additions for labelling by Russell Lang, Monash University, Australia.
.br
(rjl@monu1.cc.monash.edu.au)
.br
Further additions by David Kotz, Dartmouth College, New Hampshire, USA
(formerly of Duke University, North Carolina, USA).  
.br
(David.Kotz@Dartmouth.edu)
.br
X11 support by Ed Kubaitis, University of Illinois, USA.
.SH BUGS
The atan() function does not work correctly for complex arguments.
.br
The bessel functions do not work for complex arguments.
.br
See the 
.I help bugs
command in gnuplot.
.SH SEE ALSO
See the printed manual or the on-line help for details on specific commands.
.br
X(1).
