.\" dummy line
.TH GNUPLOT 1 "13 February 1990"
.UC 4
.SH NAME
gnuplot \- an interactive plotting program
.SH SYNOPSIS
.B gnuplot  file ...
.br
.SH DESCRIPTION
.I Gnuplot 
is a command-driven interactive function plotting program.
.PP
If files are given, 
.I gnuplot 
loads each file with the 
.I load
command, in the order specified.
.I Gnuplot 
exits after the last file is processed.
.PP
Here are some of its features:
.PP
Plots any number of functions, built up of C operators, C library
functions, and some things C doesn't have like **, sgn(), etc.  Also
support for plotting data files, to compare actual
data to theoretical curves.
.PP
User-defined X and Y ranges (optional auto-ranging), smart axes scaling,
smart tic marks.
.PP
Labelling of X and Y axes.
.PP
User-defined constants and functions.
.PP
Support through a generalized graphics driver for
AED 512,
AED 767,
BBN BitGraph,
Roland DXY800A,
EEPIC,
Epson LX-800,
Fig, 
HP2623,
HP2648,
HP75xx,
HPGL,
IBM Proprinter,
Imagen,
Iris 4D,
Kermit-MS,
LaTeX,
NEC CP6 pinwriter,
PostScript,
QMS QUIC,
ReGis (VT125 and VT2xx),
Selanar,
Tek 401x,
Vectrix 384,
and unixplot.  
The PC version compiled by Microsoft C
supports IBM CGA, EGA, VGA, Hercules, ATT 6300,
and Corona 325 graphics.  
The PC version compiled by Turbo C
supports IBM CGA, EGA, MCGA, VGA and Hercules graphics.  
Other devices can be added simply, but will require recompiling.
.PP
Shell escapes and command line substitution.
.PP
Load and save capability.
.PP
Output redirection.
.PP
All computations performed in the complex domain.  Just the real part is
plotted by default, but functions like imag() and abs() and arg() are
available to override this.
.SH AUTHORS
Thomas Williams, Pixar Corporation, 
.br
(pixar!info-gnuplot@sun.com)
.br
and Colin Kelley.
.PP
Additions for labelling by Russell Lang, Monash University, Australia.
.br
(rjl@monu1.cc.monash.edu.au)
.br
Further additions by David Kotz, Duke University, North Carolina, USA. 
.br
(dfk@cs.duke.edu)
.SH BUGS
The atan() function does not work correctly for complex arguments.
.br
See the 
.I help bugs
command in gnuplot.
.SH SEE ALSO
See the printed manual or the on-line help for details on specific commands.
