.TH GNUT2P 1
.SH NAME
gnut2p \- translate GnuTeX input file to GNUPLOT input file
.SH SYNOPSIS
.B gnut2P
infile outfile
.SH DESCRIPTION
.I gnut2p 
converts an input file for the old gnutex(1) plotting program into an
input file suitable for its successor, gnuplot(1) version 2.0.  This
program does its best, but is not perfect. Most of gnutex will
translate directly, some things will translated easily (such as \fBset
size\fR), but some things cannot be translated (such as \fBset
style\fR). One thing this program does is to move plot commands down
past the \fBlabel\fR and \fBkey\fR commands (which change into \fBset
label\fR and \fBset key\fR commands). This may move it past other
commands.  If it moves past variable or function definitions,
\fBset\fR commands, or other commands which affect the plot command's
execution, then the new version will be incorrect. I expect this case
to be rare; indeed, I generally expect the last lines in GnuTeX input
files used with LaTeX to consist of \fBplot\fR, \fBlabel\fR, and
\fBkey\fR commands.
.PP 
The usage of this program is simple. 
.I infile
is an existing GnuTeX file, and 
.I outfile
will be created as the GNUPLOT equivalent. The errors, warnings, and
explanatory comments appear on stderr. Any use of line continuation
will be lost, and some instances of the input style (eg, white space)
may be changed.

.SH SEE ALSO
gnuplot(1), gnutex(1)
.br
The "GNUPLOT" 2.0 Manual
.br
The "GnuTeX" 1.6 Manual and Tutorial
.br
"LaTeX and the GNUPLOT Plotting Program" (notes for former GnuTeX users).

.SH AUTHOR
David Kotz dfk@cs.duke.edu
