.TH HELP L
.SH NAME
help - a VMS-like help facility for XENIX
.SH SYNOPSIS
.B help
.br
.SH DESCRIPTION
.I help
is intended to be a more useful system than the native
.I man(1)
supplied with
.I XENIX.
It is styled after the very popular and useful VMS HELP facility, in that
it is tree structured and interactive.
.PP
.I help
is very configurable.  In essence, you decide what help "topics" map
to what files.  I.E. you can have more than one topic, or acronym, map
to the same help subtopic.  An example would be having the words "lp"
and "printing" both map to the 
.I help
subtopic "lp-command".  Also, you need not have the subtopic "lp" even
show up in the help screen.  If you wish to have acronyms, as described
above, it is site taylorable using the DIRFILE (as described below in
INTERNALS).
.PP
All of the files and directories contained in the system are all plain
text files, with an easy format that can be used to your advantage.
.sp 1
.SH "INTERNALS"
.I help
uses a tree structured file data-base to store all help.  Each node (or
directory) has at least one file.  This file, called
.I ./TEXT
contains the actual text of the help message for this subtopic.  If there
are any subtopics below this one, their
.I ./TEXT
files are held in subdirectories of this one, and then there is a file
.I ./DIR
that maps the directory name to the subtopic to display.  This will allow
.I SYSV
systems with limited directory name lengths map much longer descriptions
to shorter file names.
.PP
Also contained in the
.I ./DIR
file is a similar mapping for acronyms of the subsequent subtopics.  In the
example above with lp, a sample portion of a help file would be
.sp 1
	lp-command*lp
.br
	lp-command:printing
.br
	lp-command:getting output
.sp 1
Where the "*" in the first line implies that the "topic" name "lp" is to
be printed as a possible topic for help, and the subtopics "printing" and
"getting output" are acronyms for traversing the to the "lp-command"
subdirectory to get at the next
.I ./TEXT
file.
.sp 1
.SH "FILES"
"/usr/help/...."	- Root directory for help
.br
"./TEXT"			- Help text
.br
"./DIR"			- Directory files for next subtopic
.PP
.SH DIAGNOSTICS
There are no real diagnostics.  However, if you reach a point in the
help system where you know you have a "subtopic" but cannot reach it,
search for correct premissions (0444 for
.I ./TEXT
files, and (0555 for
.I ./DIR
files).
.sp 1
.SH AUTHOR
Roland J. Stolfa
.br
Department of Computing and Information Sciences
.br
Oklahoma State University

