# make file for Borland C++ 3.x
#   and Phar Lap LITE286 DOS extender
# both LITE286 bin and BORLANDC bin directories must be on the path

# where to place gnuplot.gih helpfile
HELPFILE = gnuplot.gih
# location of LITE286 Pharlap Extender
LITE=c:\lite286
LITECC=$(LITE)\bin\bcc286
# location of Turbo C compiler
TC = c:\borlandc
# name of C compiler
CC = bcc
#CC = tcc
# location of TLINK.EXE and TCC.EXE or BCC.EXE
BIN = $(TC)\bin\\
#BIN =
# location of BGI files,
# change this line if not in TC directory, i.e. $(TC)\bgi
BGI = $(TC)\bgi

# -c means don't link, -f means emulate 8087 if not present
# -ml says large model 
# -M means produce link map
# -y means include line numbers for debugger
# -v means include debug info
# -w- means ignore warnings and do not report them
# -DREADLINE to use the history/line editing capability. If you want this 
#    capability add -DREADLINE to CFLAGS
CFLAGS = -Ff=256 -c -f -ml -w- -I$(TC)\include -DMSDOS -DPC -DREADLINE
TERMFLAGS =

OBJ1 =  bitmap.obj command.obj contour.obj eval.obj graphics.obj graph3d.obj
OBJ2 =	help.obj internal.obj misc.obj parse.obj plot.obj readline.obj
OBJ3 =	scanner.obj setshow.obj specfun.obj standard.obj term.obj util.obj
OBJ4 =	version.obj gnubin.obj binary.obj
BGIFILES = cga.bgi egavga.bgi herc.bgi att.bgi

OBJS =	$(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4)

CSOURCE5 = term\aed.trm term\cgi.trm term\dumb.trm term\dxy.trm \
	term\eepic.trm term\epson.trm term\fig.trm term\hp26.trm \
	term\hp2648.trm term\hpgl.trm term\hpljii.trm 
CSOURCE6 = term\impcodes.h term\imagen.trm term\object.h \
	term\iris4d.trm term\kyo.trm term\latex.trm term\pc.trm 
CSOURCE7 = term\post.trm term\qms.trm term\regis.trm term\sun.trm \
	term\t410x.trm term\tek.trm term\unixpc.trm term\unixplot.trm \
	term\v384.trm term\x11.trm
CSOURCE8 = contour.c specfun.c gnubin.c binary.c

all: gnuplot.exe $(HELPFILE) demo\bf_test.exe $(BGIFILES)

# use response file to avoid command-line overflow
gnuplot.exe: $(OBJS)
	$(BIN)tlink @&&!
$(LITE)\bc3\lib\c0pl +
bitmap command eval graphics graph3d help internal misc parse +
plot scanner setshow specfun standard term util version contour +
gnubin binary +
readline +
$(LITE)\bc3\lib\emu286.lib +
,gnuplot,gnuplot, +
$(TC)\lib\emu +
$(TC)\lib\mathl +
$(LITE)\bc3\lib\graph286.lib +
$(LITE)\bc3\lib\phapi +
$(LITE)\bc3\lib\bcl286, +
gnuplot.def
!


# default rules

.c.obj:
	$(LITECC) $(CFLAGS) $<

bitmap.obj: bitmap.c bitmap.h plot.h

command.obj: command.c plot.h setshow.h help.h
	$(LITECC) $(CFLAGS) command.c

contour.obj: contour.c plot.h

eval.obj: eval.c plot.h

graphics.obj: graphics.c plot.h setshow.h

graph3d.obj: graphics.c plot.h setshow.h

help.obj: help.c plot.h help.h

internal.obj: internal.c plot.h

misc.obj: misc.c plot.h setshow.h help.h

parse.obj: parse.c plot.h
	$(LITECC) $(CFLAGS) parse.c

plot.obj: plot.c plot.h setshow.h
	$(LITECC) $(CFLAGS) plot.c

readline.obj: readline.c

scanner.obj: scanner.c plot.h

setshow.obj: setshow.c plot.h setshow.h

specfun.obj: specfun.c

standard.obj: standard.c plot.h

# the CSOURCE? dependencies are not up to date (but who cares)
term.obj: term.c term.h plot.h setshow.c bitmap.h $(CSOURCE5) $(CSOURCE6) $(CSOURCE7)
	$(LITECC) $(CFLAGS) $(TERMFLAGS) -Iterm term.c

util.obj: util.c plot.h

version.obj: version.c

# convert gnuplot.doc to gnuplot.gih
$(HELPFILE): doc2gih.exe docs\gnuplot.doc
	doc2gih docs\gnuplot.doc $(HELPFILE)

doc2gih.exe: docs\doc2gih.c
    $(BIN)$(CC) -w- -ml -I$(TC)\include -L$(TC)\lib docs\doc2gih.c

demo\bf_test.exe: bf_test.c binary.obj
    $(BIN)$(CC) -edemo\bf_test.exe -w- -ml -I$(TC)\include -L$(TC)\lib bf_test.c binary.obj

# copy Borland Graphics Interface files to current directory
cga.bgi: $(BGI)\cga.bgi
	copy $(BGI)\$< $<

egavga.bgi: $(BGI)\egavga.bgi
	copy $(BGI)\$< $<

herc.bgi: $(BGI)\herc.bgi
	copy $(BGI)\$< $<

att.bgi: $(BGI)\att.bgi
	copy $(BGI)\$< $<

# clean target - remove all temp files, but leave executable intact
# needed when changing configuration (model or overlaying)

clean:
	del *.obj
	del gnuplot.map
	del doc2gih.exe

# realclean target - remove all files created by the makefile

realclean: clean
	del gnuplot.exe
	del gnuplot.gih
	del demo\bf_test.exe
	del demo\binary1
	del demo\binary2
	del demo\binary3
