#
# Make file for Microsoft C  Version 7.0 Windows NT Version
# and Microsoft Program Maintenance Utility  Version 1.20
# 

# This has never been tried

# I do not have access to Windows NT so I have not tested any of this.
# I don't even know if WIN32 is the appropriate #define to use!  
# If it isn't feel free to change all occurences to the standard #define.
# If you make changes further changes for Windows NT, make sure that 
# gnuplot still works with Windows 3.0.
# Also, gnuplot for Windows NT should be built WITHOUT using a DLL - compile 
# without setting __DLL__ and then link all modules into a single EXE.
# rjl 1993-02-01

# where to place gnuplot.gih helpfile
HELPFILE = wgnuplot.hlp
TOP = .

# /c  means don't link
# /AL means large memory model (large code, large data)
# /W1 means lower warning level
# /I  means extra include directory
# /GA means windows application
# /Fm means produce link map
# /Od means suppress optimizations (esp. for debug)
# /Zi mean prepare for codeview
CFLAGS = /c /ALw /FmGNUPLOT /GA /W1 /D__MSC__ /DREADLINE /DWIN32 /I$(TOP) #/Zi #/Od

# see other terminal defines in term.h
TERMFLAGS = 

# /NOE means NO EXTernal Dictionary
# /NOI means NO ignore case
# /NOD means no default library (or :specified)
# /CO prepare for codeview
LINKFLAGS = /NOE /NOI /NOD:LLIBCE /ONERROR:NOEXE #/CO 

OBJS =  bitmap.obj command.obj contour.obj eval.obj graphics.obj graph3d.obj \
	internal.obj misc.obj parse.obj plot.obj readline.obj scanner.obj \
	setshow.obj specfun.obj standard.obj term.obj util.obj version.obj \
	gnubin.obj binary.obj winmain.obj

CSOURCE5 = term\aed.trm term\cgi.trm term\dumb.trm term\dxy.trm \
	term\eepic.trm term\epson.trm term\fig.trm term\hp26.trm \
	term\hp2648.trm term\hpgl.trm term\hpljii.trm 
CSOURCE6 = term\impcodes.h term\imagen.trm term\object.h \
	term\iris4d.trm term\kyo.trm term\latex.trm term/pbm.trm term\win.trm
CSOURCE7 = term\post.trm term\qms.trm term\regis.trm term\sun.trm \
	term\t410x.trm term\tek.trm term\unixpc.trm term\unixplot.trm \
	term\v384.trm term\x11.trm
CSOURCE8 = contour.c specfun.c gnubin.c binary.c
WINDOWS = makefile.win makefile.msw README.win win\wcommon.h \
	win\wgnuplib.c win\wgnuplib.def win\wgnuplib.h win\wgnuplib.rc\
	win\wgnuplot.def win\wgnuplot.hpj win\wgnuplot.mnu win\wgnuplot.rc \
	win\wgraph.c win\winmain.c win\wmenu.c win\wpause.c \
	win\wprinter.c win\wresourc.h win\wtext.c win\wtext.h \
	win\geticon.c docs\doc2rtf.c term\win.trm

default: wgnuplot.exe $(HELPFILE) wgnuplot.mnu demo\bf_test.exe

# default rules
.c.obj:
	cl $(CFLAGS) $*.c

linkopt1.msw: makefile.msw
	echo winmain+bitmap+command+eval+graphics+ >linkopt1.msw
	echo graph3d+internal+misc+parse+ >>linkopt1.msw
	echo plot+scanner+setshow+specfun+ >>linkopt1.msw
	echo standard+term+util+version+contour+ >>linkopt1.msw
	echo gnubin+binary+readline+ >>linkopt1.msw
	echo wgnuplib+wtext+wmenu+wpause+wgraph+wprinter > linkopt1.msw
	echo wgnuplot,wgnuplot, >>linkopt1.msw
	echo libw+commdlg+shell+ldllcew >> linkopt1.msw
	echo win\wgnuplot.def >>linkopt1.msw
	echo ; >>linkopt1.msw

wgnuplot.exe: $(OBJS) win\wgnuplot.def win\wgnuplot.rc win\wgnuplib.rc winmain.obj linkopt1.msw texticon.ico grpicon.ico
	link $(LINKFLAGS) @linkopt1.msw
	rc -k -dMSRC win\wgnuplot.rc wgnuplot.exe

# rules

binary.obj: binary.c 

bitmap.obj: bitmap.c bitmap.h plot.h

command.obj: command.c plot.h setshow.h help.h
	cl $(CFLAGS) /DHELPFILE=\"$(HELPFILE)\" command.c

contour.obj: contour.c plot.h

eval.obj: eval.c plot.h

gnubin.obj: gnubin.c

graphics.obj: graphics.c plot.h setshow.h

graph3d.obj: graphics.c plot.h setshow.h

help.obj: help.c plot.h help.h

internal.obj: internal.c plot.h

misc.obj: misc.c plot.h setshow.h

parse.obj: parse.c plot.h

plot.obj: plot.c plot.h setshow.h

readline.obj: readline.c

scanner.obj: scanner.c plot.h

setshow.obj: setshow.c plot.h setshow.h

standard.obj: standard.c plot.h

specfun.obj: specfun.c plot.h

term.obj: term.c term.h plot.h setshow.h bitmap.h $(CSOURCE5) $(CSOURCE6) $(CSOURCE7)
	cl $(CFLAGS) $(TERMFLAGS) /Iterm term.c

util.obj: util.c plot.h

version.obj: version.c

winmain.obj: win\winmain.c win\wgnuplib.h win\wtext.h plot.h
	cl $(CFLAGS) /DHELPFILE=\"$(HELPFILE)\"  win\winmain.c

wgnuplib.obj: win/wgnuplib.c win/wgnuplib.h win/wcommon.h win/wresourc.h
	
wmenu.obj: win/wmenu.c win/wgnuplib.h win/wcommon.h win/wresourc.h

wtext.obj: win/wtext.c win/wgnuplib.h win/wcommon.h win/wresourc.h
	
wpause.obj: win/wpause.c win/wgnuplib.h win/wcommon.h win/wresourc.h
	
wprinter.obj: win/wprinter.c win/wgnuplib.h win/wcommon.h win/wresourc.h
	
wgraph.obj: win/wgraph.c win/wgnuplib.h win/wcommon.h win/wresourc.h
	
wgnuplot.mnu: win\wgnuplot.mnu
	copy win\wgnuplot.mnu wgnuplot.mnu

# extract icons from wgnuplot.rc
texticon.ico: grpicon.ico

grpicon.ico: geticon.exe win\wgnuplot.rc
	geticon win\wgnuplot.rc

geticon.exe: win\geticon.c
	cl /AL /DMSDOS /F 5000 /Gt /W1 win\geticon.c


# convert gnuplot.doc to gnuplot.gih
$(HELPFILE): doc2rtf.exe docs\gnuplot.doc win\wgnuplot.hpj
	doc2rtf docs\gnuplot.doc win\gnuplot.rtf
	hc31 win\wgnuplot.hpj 

doc2rtf.exe: docs\doc2rtf.c
	cl /AL /DMSDOS /F 5000 /Gt /W1 docs\doc2rtf.c

#make binary demo files
demo\bf_test.exe: bf_test.c dbinary.obj
        cl /AL /D__MSC__ /F 5000 /Gt /W1 /Fedemo\bf_test.exe bf_test.c dbinary.obj
	cd demo
	bf_test
	cd ..

dbinary.obj: binary.c
        cl /c /AL /D__MSC__ /F 5000 /Gt /W1 /Fodbinary.obj binary.c

# clean up temporary files
clean:
	del *.obj
	del wgnuplot.map
	del win\wgnuplot.res
	del win\gnuplot.rtf
	del doc2rtf.exe
	del demo\bf_test.exe
	del linkopt1.msw
        del *.ico
        del geticon.exe
	
veryclean: clean
	del wgnuplot.exe
	del wgnuplot.hlp
	del wgnuplot.mnu
	del demo\binary1
	del demo\binary2
	del demo\binary3
