#! /bin/sh --
# $Id: prepare,v 1.2 2001/06/20 14:47:57 amai Exp $
# Small shell script to prepare the gnuplot sources when
# checked out from CVS.

exelist="configure configure.vms install-sh missing mkinstalldirs config/djconfig.sh lisp/configure"

chmod 755 $exelist >/dev/null 2>&1

# Clean up
rm -f config.cache config.status

if aclocal -I m4 && autoheader && (cd m4 && make -f Makefile.am.in ) \
  && automake -a -c  && autoconf
then
  echo
  echo "The gnuplot source code was successfully prepared."
  echo "Run configure now, then make && make install to build and install gnuplot."
  echo
else
  echo
  echo "Some part of the preparation process failed."
  echo "Please refer to INSTALL for details."
  echo
  exit 1
fi
