#! /bin/sh --
# $Id: prepare,v 1.3 2001/08/22 14:17:59 broeker Exp $
# Small shell script to prepare the gnuplot sources when
# checked out from CVS.

exelist="configure configure.vms install-sh missing mkinstalldirs config/djconfig.sh lisp/configure"

chmod 755 $exelist >/dev/null 2>&1

# Clean up
rm -f config.cache config.status

if aclocal -I m4 && autoheader && (cd m4 && make -f Makefile.am.in ) \
  && automake -a -c \
  && sed 's/noinst_PROGRAMS = bf_test$(EXEEXT) @GNUPLOT_X11@/noinst_PROGRAMS = bf_test$(EXEEXT) @GNUPLOT_X11@$(EXEEXT)/' \
	<src/makefile.in >src/makefile.in2 \
  && mv -f src/makefile.in2 src/makefile.in \
  && autoconf
then
  echo
  echo "The gnuplot source code was successfully prepared."
  echo "Run configure now, then make && make install to build and install gnuplot."
  echo
else
  echo
  echo "Some part of the preparation process failed."
  echo "Please refer to INSTALL for details."
  echo
  exit 1
fi
