all: html

distclean: clean
clean:
	rm -f *.png *.gnu *.html *.js *.dat epslatex* fit.log soundfit.par *.?.svg *.??.svg

GNUPLOT_LIB = ..

#
# Auto-generation of the svg demo set.
#
html: airfoil.html approximate.html arrowstyle.html binary.html bivariat.html candlesticks.html circles.html contours.html controls.html datastrings.html discrete.html electron.html ellipse.html enhanced_utf8.html fillbetween.html fillcrvs.html fillstyle.html finance.html hidden.html hidden2.html histograms.html histograms2.html index.html iterate.html key.html layout.html margins.html mgr.html multiaxis.html multimsh.html multiplt.html param.html pm3dcolors.html pm3d.html pointsize.html polar.html poldat.html prob2.html prob.html rainbow.html random.html rectangle.html rgb_variable.html running_avg.html scatter.html simple.html singulr.html smooth.html spline.html steps.html stringvar.html surface1.html surface2.html transparent.html transparent_solids.html textcolor.html textrotate.html tics.html timedat.html using.html vector.html world.html world2.html dashcolor.html heatmaps.html

index.html: index.svg
	cp index.svg index.html

dashcolor.html: $(GNUPLOT_LIB)/dashcolor.dem ./webify_svg.pl
	export DEMOTERM="svg dashed enhanced font 'arial,11' size 600,400 dynamic"; ./webify_svg.pl dashcolor

%.html: $(GNUPLOT_LIB)/%.dem ./webify_svg.pl
	./webify_svg.pl $*

