#
# $Id: makefile.286,v 1.6 2007/10/16 21:19:43 sfeam Exp $
#
# GNUPLOT Makefile for Borland C++ 3.x
#   and Phar Lap LITE286 DOS extender
#
# both LITE286 bin and BORLANDC bin directories must be on the path

# where to place gnuplot.gih helpfile
HELPFILE = gnuplot.gih
# location of LITE286 Pharlap Extender
LITE=c:\lite286
LITECC=$(LITE)\bin\bcc286
# location of Turbo C compiler
TC = c:\borlandc
# name of C compiler
CC = bcc
#CC = tcc
# location of TLINK.EXE and TCC.EXE or BCC.EXE
BIN = $(TC)\bin\\
#BIN =
# location of BGI files,
# change this line if not in TC directory, i.e. $(TC)\bgi
BGI = $(TC)\bgi

# -c means don't link, -f means emulate 8087 if not present
# -ml says large model 
# -M means produce link map
# -y means include line numbers for debugger
# -v means include debug info
# -w- means ignore warnings and do not report them
# -DREADLINE to use the history/line editing capability. If you want this 
#    capability add -DREADLINE to CFLAGS
CFLAGS = -Ff=256 -c -f -ml -w- -I$(TC)\include -DMSDOS -DPC -DREADLINE -DHAVE_STRNICMP
TERMFLAGS =

OBJ1 = alloc.obj binary.obj bitmap.obj command.obj contour.obj datafile.obj
OBJ2 = dynarray.obj eval.obj fit.obj graph3d.obj graphics.obj help.obj
OBJ3 = history.obj hidden3d.obj internal.obj interpol.obj matrix.obj misc.obj
OBJ4 = parse.obj plot.obj plot2d.obj plot3d.obj readline.obj save.obj
OBJ5 = scanner.obj set.obj show.obj specfun.obj standard.obj stdfn.obj
OBJ6 = tables.obj tabulate.obj term.obj time.obj unset.obj util.obj util3d.obj
OBJ7 = variable.obj version.obj

BGIFILES = cga.bgi egavga.bgi herc.bgi att.bgi

OBJS =	$(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4) $(OBJ5) $(OBJ6) $(OBJ7)

CSOURCE5 = term\aed.trm term\cgi.trm term\dumb.trm term\dxy.trm \
	term\eepic.trm term\epson.trm term\fig.trm term\hp26.trm \
	term\hp2648.trm term\hpgl.trm term\hpljii.trm 
CSOURCE6 = term\impcodes.h term\imagen.trm term\object.h \
	term\kyo.trm term\latex.trm term\pc.trm 
CSOURCE7 = term\post.trm term\qms.trm term\regis.trm term\sun.trm \
	term\t410x.trm term\tek.trm term\unixpc.trm term\unixplot.trm \
	term\v384.trm term\x11.trm
CSOURCE8 = contour.c specfun.c binary.c interpol.c

all: gnuplot.exe $(HELPFILE) demo\bf_test.exe $(BGIFILES)

# use response file to avoid command-line overflow
gnuplot.exe: $(OBJS)
	$(BIN)tlink @&&!
$(LITE)\bc3\lib\c0pl +
bitmap command eval graphics graph3d help internal misc parse +
plot scanner setshow specfun standard stdfn term util version contour +
binary interpol datafile alloc +
readline +
$(LITE)\bc3\lib\emu286.lib +
,gnuplot,gnuplot, +
$(TC)\lib\emu +
$(TC)\lib\mathl +
$(LITE)\bc3\lib\graph286.lib +
$(LITE)\bc3\lib\phapi +
$(LITE)\bc3\lib\bcl286, +
gnuplot.def
!


# default rules

.c.obj:
	$(LITECC) $(CFLAGS) $<

alloc.obj: alloc.c alloc.h plot.h

bitmap.obj: bitmap.c bitmap.h plot.h

command.obj: command.c plot.h setshow.h help.h
	$(LITECC) $(CFLAGS) command.c

contour.obj: contour.c plot.h

datafile.obj: datafile.h plot.h

dynarray.obj: dynarray.h ploy.h

eval.obj: eval.c plot.h

fit.obj: fit.c fit.h matrix.h plot.h

graph3d.obj: graphics.c plot.h setshow.h

graphics.obj: graphics.c plot.h setshow.h

help.obj: help.c plot.h help.h

history.obj: history.c gp_hist.h plot.h

internal.obj: internal.c plot.h

interpol.obj: interpol.c plot.h setshow.h

matrix.obj: matrix.c matrix.h fit.h

misc.obj: misc.c plot.h setshow.h help.h

parse.obj: parse.c plot.h
	$(LITECC) $(CFLAGS) parse.c

plot.obj: plot.c plot.h setshow.h
	$(LITECC) $(CFLAGS) plot.c

readline.obj: readline.c

save.obj: save.c plot.h ansichek.h stdfn.h syscfg.h

scanner.obj: scanner.c plot.h

set.obj: set.c plot.h setshow.h

show.obj: show.c plot.h setshow.h

specfun.obj: specfun.c

standard.obj: standard.c plot.h

stdfn.obj: stdfn.c stdfn.h

# the CSOURCE? dependencies are not up to date (but who cares)
term.obj: term.c term.h plot.h setshow.c bitmap.h $(CSOURCE5) $(CSOURCE6) $(CSOURCE7)
	$(LITECC) $(CFLAGS) $(TERMFLAGS) -Iterm -I. term.c

time.obj:  time.c gp_time.h plot.h

unset.obj: unset.c plot.h ansichek.h stdfn.h syscfg.h

util.obj: util.c plot.h

variable.obj: variable.c plot.h variable.h

version.obj: version.c

# convert gnuplot.doc to gnuplot.gih
$(HELPFILE): doc2gih.exe docs\gnuplot.doc
	doc2gih docs\gnuplot.doc $(HELPFILE)

doc2gih.exe: docs\doc2gih.c docs\termdoc.c
    $(BIN)$(CC) -edoc2gih.exe -w- -ml -I$(TC)\include -L$(TC)\lib docs\doc2gih.c docs\termdoc.c

demo\bf_test.exe: bf_test.c binary.obj alloc.obj
    $(BIN)$(CC) -edemo\bf_test.exe -w- -ml -I$(TC)\include -L$(TC)\lib bf_test.c binary.obj alloc.obj

# copy Borland Graphics Interface files to current directory
cga.bgi: $(BGI)\cga.bgi
	copy $(BGI)\$< $<

egavga.bgi: $(BGI)\egavga.bgi
	copy $(BGI)\$< $<

herc.bgi: $(BGI)\herc.bgi
	copy $(BGI)\$< $<

att.bgi: $(BGI)\att.bgi
	copy $(BGI)\$< $<

# clean target - remove all temp files, but leave executable intact
# needed when changing configuration (model or overlaying)

clean:
	del *.obj
	del gnuplot.map
	del doc2gih.exe

# realclean target - remove all files created by the makefile

realclean: clean
	del gnuplot.exe
	del gnuplot.gih
	del demo\bf_test.exe
	del demo\binary1
	del demo\binary2
	del demo\binary3
